[package]
name    = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow     = "1.0.68"
clap       = { version = "4.1.1", features = ["derive"] }
env_logger = "0.10.0"
log        = "0.4.17"
svd2rust   = "0.28.0"
svdtools = "0.2.7"
xshell     = "0.2.3"
