[package]
name    = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow     = "1.0.66"
clap       = { version = "4.0.22", features = ["derive"] }
env_logger = "0.9.3"
log        = "0.4.17"
svd2rust   = "0.27.2"
