[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

rustflags = [
    "-C", "link-arg=-Tlinkall.x",

    "-C", "link-arg=-Trom_coexist.x",
    "-C", "link-arg=-Trom_functions.x",
    "-C", "link-arg=-Trom_phy.x",

    "-C", "force-frame-pointers",
]

[build]
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = [ "core" ]
