[package]
name = "esp-ieee802154"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = { version = "1.1.1", optional = true }
riscv = "0.10.0"
riscv-rt = { version = "0.10.0", optional = true }
vcell = "0.1.3"
