[package]
name = "esp-ieee802154"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
critical-section = { version = "1.1.1" }
log = "0.4.17"
vcell = "0.1.3"
heapless = "0.7.16"
ieee802154 = "0.6.1"
byte = "0.2.6"

esp32c6-hal = { version = "0.1.0", optional = true }
esp32c6 = { version = "0.3.0", optional = true }

[dev-dependencies]
esp-println = { version = "0.4.0", features = [ "esp32c6", "log" ] }
esp-backtrace = { version = "0.6.0", features = ["esp32c6", "panic-handler", "exception-handler", "print-uart"] }
log = "0.4.17"

[features]
default = []
esp32h4 = []
esp32c6 = ["esp32c6-hal", "dep:esp32c6"]

[patch.crates-io]
esp32c6-hal = { path = "/projects/esp/esp-hal/esp32c6-hal" }
