[package]
name = "esp-ieee802154"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = "1.1.1"
log = "0.4.18"
vcell = "0.1.3"
heapless = "0.7.16"
ieee802154 = "0.6.1"
byte = "0.2.6"

esp32c6 = { version = "0.4.0", optional = true }
esp32c6-hal = { version = "0.2.0", optional = true }

esp32h2 = { package = "esp32h2", git = "https://github.com/esp-rs/esp-pacs", rev = "9803373", optional = true }
esp32h2-hal = { package = "esp32h2-hal", git = "https://github.com/esp-rs/esp-hal", rev = "fbe4ed1", optional = true }

# FIXME: should be dev-depenedencies
esp-println = { version = "0.5.0", features = ["log"] }
esp-backtrace = { version = "0.7.0", features = ["panic-handler", "exception-handler", "print-uart"] }

[features]
default = []
esp32c6 = ["dep:esp32c6-hal", "dep:esp32c6", "esp-println/esp32c6", "esp-backtrace/esp32c6"]
esp32h2 = ["dep:esp32h2-hal", "dep:esp32h2", "esp-println/esp32h2", "esp-backtrace/esp32h2"]

[profile.release]
debug = true
