[package]
name = "esp-ieee802154"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = { version = "1.1.1", optional = true }
log = "0.4.17"
riscv = "0.10.1"
vcell = "0.1.3"

[features]
default = []
esp32h4 = []
