[package]
name = "esp-ieee802154"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
critical-section = { version = "1.1.1" }
log = "0.4.17"
vcell = "0.1.3"

esp32c6-hal = { git = "https://github.com/esp-rs/esp-hal", package = "esp32c6-hal", rev = "7cf7d8eeac9172b24f0fba7ae659ec39925ce04f", optional = true }
esp32c6 = { version = "0.1.0", optional = true }

[dev-dependencies]
esp-println = { version = "0.4.0", features = [ "esp32c6", "log" ] }
esp-backtrace = { version = "0.6.0", features = ["esp32c6", "panic-handler", "exception-handler", "print-uart"] }
log = "0.4.17"

[features]
default = []
esp32h4 = []
esp32c6 = ["esp32c6-hal", "dep:esp32c6"]

[patch.crates-io]
esp32c6 = { path="/projects/esp/esp-pacs/esp32c6" }

[patch.'https://github.com/esp-rs/esp-hal']
esp32c6-hal ={ path = "/projects/esp/esp-hal/esp32c6-hal" }
